export const rules = [
  'Respect Other Players: Treat everyone with kindness and respect, regardless of their skill level or in-game actions.',
  'No Harassment or Hate Speech: Do not engage in any form of harassment, hate speech, or offensive language towards other players.',
  "Follow Lobby Guidelines: Abide by the specific lobby's rules and objectives, whether it's sandbox exploration, chase, or custom gamemodes.",
  'No Cheating or Hacking: Do not use any cheats, hacks, or third-party software that provide an unfair advantage. Play fair!',
  "Listen to Admins: Follow instructions given by server administrators and moderators. They're here to ensure a smooth experience for everyone.",
  "No Griefing: Do not intentionally disrupt other players' experiences through excessive trolling or griefing.",
  'No Spawn Killing: Avoid repeatedly killing players immediately after they spawn. Allow them a fair chance to participate.',
  'Use Common Sense: Make decisions in-game that reflect common sense and fairness, even in custom lobbies or sandbox.',
  'No Exploiting: Refrain from exploiting glitches, bugs, or unintended mechanics for personal gain.',
  "Respect Custom Lobby Rules: If you're in a custom lobby with specific rules, follow those guidelines to maintain a fun and balanced experience.",
  'Report Rule Violations: If you witness someone breaking the rules, report it to a moderator or admin instead of taking matters into your own hands.',
  "No Excessive Spamming: Avoid spamming text or voice chat, as it can disrupt others' gameplay and communication.",
  "Play Responsibly: If you're driving vehicles or engaging in combat, do so responsibly to prevent unnecessary chaos.",
  "Help Newcomers: If you're an experienced player, assist newcomers and provide guidance to help them enjoy their time on the server.",
  'Have Fun Together: Ultimately, the goal is to have a good time together. Foster a positive community and enjoy the diverse experiences the server offers.',
];
