export default {
  OFF: '',
  WIDE: 'ANIM_GROUP_MOVE_BALLISTIC',
  Lamar: 'ANIM_GROUP_MOVE_LEMAR_ALLEY',
  Angry: 'clipset@move@trash_fast_turn',
  'Like a Karen': 'FEMALE_FAST_RUNNER',
  'Garbage bag': 'missfbi4prepp1_garbageman',
  Wide: 'move_characters@franklin@fire',
  Slow: 'move_characters@Jimmy@slow@',
  'Other wide': 'move_characters@michael@fire',
  'Like a Karen2': 'move_f@flee@a',
  Scared: 'move_f@scared',
  Sexy: 'move_f@sexy@a',
  Lester: 'move_heist_lester',
  'Broken leg': 'move_injured_generic',
  Lester2: 'move_lester_CaneUp',
  'Other wide2': 'move_m@bag',
  Sad: 'MOVE_M@BAIL_BOND_NOT_TAZERED',
  'Very sad': 'MOVE_M@BAIL_BOND_TAZERED',
  Excited: 'move_m@brave',
  'Casual chill': 'move_m@casual@d',
  'Moderate drunk': 'move_m@drunk@moderatedrunk',
  Drunk: 'MOVE_M@DRUNK@MODERATEDRUNK_HEAD_UP',
  'A little drunk': 'MOVE_M@DRUNK@SLIGHTLYDRUNK',
  DRUNK: 'MOVE_M@DRUNK@VERYDRUNK',
  Fireman: 'move_m@fire',
  Gang: 'move_m@gangster@var_e',
  'Walking in rain': 'move_m@gangster@var_f',
  'Inconspicuously fast': 'move_m@gangster@var_i',
  Confident: 'move_m@JOG@',
  'Weapon in hand': 'MOVE_M@PRISON_GAURD',
  'Other wide3': 'MOVE_P_M_ONE',
  Confident2: 'MOVE_P_M_ONE_BRIEFCASE',
  'Other wide4': 'move_p_m_zero_janitor',
  'Very slow': 'move_p_m_zero_slow',
  'Slow in hurry': 'move_ped_bucket',
  Crouch: 'move_ped_crouched',
  Focused: 'move_ped_mop',
  Sexy2: 'MOVE_M@FEMME@',
  Sexy3: 'MOVE_F@FEMME@',
  Sexy4: 'MOVE_M@GANGSTER@NG',
  Sexy5: 'MOVE_M@POSH@',
  Sexy6: 'MOVE_F@POSH@',
  'Like a real gangster': 'MOVE_M@TOUGH_GUY@',
  Sexy7: 'MOVE_F@TOUGH_GUY@',
};
